.github/workflows/ci.yml, .github/workflows/format.yml, brain/examples/oak/main.py, brain/setup.cfg, brain/tests/test_oak.py
- add mypy in the ci for `tests` and `examples`
- fixes oak example import
=> add mypy checks

website/docs/contribute/website.mdx
=> Clarify / expand docs contributing instructions

website/docs/brain/custom-applications.mdx
copy paste from: https://github.com/farm-ng/amiga-app-template#readme
=> update docs to create custom app

website/docs/brain/custom-applications.mdx
cookiecutter is not used anymore
=> remove cookiecutter install step

website/docs/amiga_quick_start/amiga-quick-start.md, website/docs/brain/README.md, website/docs/dashboard/README.md, website/docs/examples/examples_index.md, website/docs/examples/file_reader/README.md, website/docs/examples/file_reader_can/README.md, website/docs/examples/import_log_file/README.md, website/docs/index.md, website/sidebars.js
Adding a page about how to record field data and how to transfer it to your local machine from the amiga. I also added the YouTube videos to the website.
=> record-and-access-data

website/docs/brain/custom-applications.mdx, website/docs/examples/import_log_file/README.md, website/docs/index.md, website/docs/tutorials/camera_streamer/01_template_starter.md, website/docs/tutorials/camera_streamer/02_kivy_definition.md, website/docs/tutorials/camera_streamer/03_camera_stream.md, website/docs/tutorials/introduction/02_template_overview.md, website/docs/tutorials/virtual_joystick/00_overview.md, website/docs/tutorials/virtual_joystick/01_template_starter.md, website/docs/tutorials/virtual_joystick/02_device_streams.md, website/docs/tutorials/virtual_joystick/03_virtual_joystick_widget.md
I added the ssh password information and added more information to the custom app development pages.
=> adding ssh password per request of students and fixing custom dev

website/docs/examples/file_reader/README.md
=> Update file reader sample url

website/docs/examples/import_log_file/README.md
I added how to format the drive and some new instructions for how to file transfer with the new changes to the app.
=> Format drive

website/docs/concepts/recorder_service/README.md, website/sidebars.js
Addressing: https://github.com/farm-ng/amiga-dev-kit/issues/218
=> Concepts - Recorder Service

website/sidebars.js
=> Add Multi Client Examples back to docs

website/docs/examples/track_follower/README.md, website/docs/examples/track_plotter/README.md, website/sidebars.js
Accompanies:
- https://github.com/farm-ng/farm-ng-amiga/pull/168
=> Add 'Plot a Track' example

website/docs/brain/custom-applications-kivy.mdx, website/docs/brain/custom-applications.mdx, website/sidebars.js
=> tutorial for custom kivy apps

website/docs/brain/sdk-barley-migration.mdx, website/sidebars.js
depends on https://github.com/farm-ng/amiga-dev-kit/pull/252
=> add migration guide to os 2

website/docs/brain/custom-applications.mdx
Motivation: https://github.com/farm-ng/workspace/issues/2308#event-11403765289
=> Instructions for App Ownership and Access

website/docs/release-notes/2024-01-17-version-220.md
Note the bugfixes and feature the Kivy examples.
=> Update 2.2 release notes for 2.2.1 patch release.

website/docs/examples/pendant_state/README.md
Was meant to be included before automerge
=> Fix typos - #278 follow-up

website/docs/concepts/system_overview/README.md, website/docs/examples/camera_aruco_detector/README.md, website/docs/examples/camera_calibration/README.md, website/docs/examples/camera_client/README.md, website/docs/examples/camera_pointcloud/README.md, website/docs/examples/camera_settings/README.md, website/docs/examples/filter_client/README.md, website/docs/examples/gps_client/README.md, website/docs/examples/motor_state/README.md, website/docs/examples/multi_client_geoimage/README.md, website/docs/examples/square_track/README.md, website/docs/examples/tool_control/README.md, website/docs/examples/track_follower/README.md, website/docs/examples/track_recorder/README.md
Motivation: https://github.com/farm-ng/amiga-dev-kit/issues/279
=> Update tailscale name resolution on examples

website/docs/examples/camera_aruco_detector/README.md, website/docs/examples/camera_calibration/README.md, website/docs/examples/camera_client/README.md, website/docs/examples/camera_pointcloud/README.md, website/docs/examples/camera_settings/README.md, website/docs/examples/events_recorder/README.md, website/docs/examples/file_converter/README.md, website/docs/examples/file_reader/README.md, website/docs/examples/file_reader_can/README.md, website/docs/examples/file_reader_gps/README.md, website/docs/examples/file_reader_headers/README.md, website/docs/examples/filter_client/README.md, website/docs/examples/gps_client/README.md, website/docs/examples/motor_state/README.md, website/docs/examples/multi_client_geoimage/README.md, website/docs/examples/multi_client_subscriber/README.md, website/docs/examples/pendant_state/README.md, website/docs/examples/square_track/README.md, website/docs/examples/tool_control/README.md, website/docs/examples/track_follower/README.md, website/docs/examples/track_planner/README.md, website/docs/examples/track_recorder/README.md, website/docs/examples/vehicle_twist/README.md, website/sidebars.js
=> More consistent example instructions

website/docs/examples/dashboard_settings/README.md
Corresponds to changes in:
- https://github.com/farm-ng/farm-ng-amiga/pull/189
=> Update dashboard settings example

website/docs/examples/examples_index.md
Motivation: https://github.com/farm-ng/Amiga-support-issues/issues/243
=> Add disclaimer about example

website/docs/examples/events_recorder/README.md
First merge https://github.com/farm-ng/workspace/pull/2730, and then https://github.com/farm-ng/farm-ng-amiga/pull/195
=> Update events recorder

website/docs/examples/cansniffer/README.md, website/docs/examples/hello_main_loop/README.md
Based on conversation with @MScatolin
=> Add notes about serial connection stability

website/docs/support/survey.md
added one page to serve as the trigger os support CSAT survey
=> add survey page
